### ISSUE TITLE
Market Auto Pricing

### ISSUE THREAD

**Issue by rollin340** [rodmk/legacy_enhancement_suite#15]
function autoUpdateStandPricing
**************************************
var price_text = $("font.darktext > font:contains('" + selected_item + "')")
      .filter(function() { return $(this).text() === selected_item; })
      .closest('tbody')
      .find("font:contains('each')");
**************************************
It should be:
var price_text = $("font.darktext > font:contains('" + selected_item + "')")
      .filter(function() { return $(this).text() === selected_item; })
      .closest('tbody')
      .find("td:contains('each')");

**Comment by rodmk** [comment]
The difference is the font:contains vs td:contains at the end, yeah? Sounds like a simple fix. 

@danielh70 wanna give this issue a go? Should make for good practice 😄

**Comment by rodmk** [comment]
Should be fixed now by #17 

Thanks for reporting the issue 😃
